# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07b62c9f8d8df4a2fadd54eb385ad8605b26561d07039b19ca412dff7c42e1b2f531134f4b3272474444ae12ba84764bca33df3246c55d241d93b2a29ff3e7af

test:
  secret_key_base: 72673d488723c7b0365167bfa7f8f6380d61d69d006c788e61d35fd8ed7cdb71215ef4992060499833d7eb1c6400d7d5fa924c5bd1fdfe2ef94f1ca3e767877a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
